// ADR-030 — Postgres sibling of ToolInvocationsRepository (TASK-681).
//
// id column is BIGINT GENERATED BY DEFAULT AS IDENTITY (Postgres replacement
// for SQLite's INTEGER PRIMARY KEY autoincrement). ok is native BOOLEAN, so
// the SQLite-side `SUM(1 - ok)` for the error count becomes the cleaner
// `COUNT(*) FILTER (WHERE NOT ok)` here.
//
// node-pg returns BIGINT / numeric as strings (to avoid precision loss above
// 2^53). Counts and avgDurationMs are safe to coerce via Number() at our
// usage scale (millions of rows at most).

import type { PgConnection } from './connection'
import type {
  ToolInvocation,
  ToolInvocationAggregate,
  ToolInvocationOperations,
  ToolInvocationWindow
} from '../../interfaces/tool-invocations-repository.interface'

interface AggregateDbRow {
  tool: string
  calls: string
  errors: string
  avg_duration_ms: string | null
  last_used_at: string
}

export class PostgresToolInvocationsRepository implements ToolInvocationOperations {
  constructor(private readonly conn: PgConnection) {}

  async recordToolInvocation(invocation: ToolInvocation): Promise<void> {
    await this.conn.query(
      `INSERT INTO tool_invocations (tool_name, ts, duration_ms, ok, error_kind)
       VALUES ($1, $2, $3, $4, $5)`,
      [
        invocation.toolName,
        invocation.ts,
        invocation.durationMs,
        invocation.ok,
        invocation.errorKind
      ]
    )
  }

  async countToolInvocations(): Promise<number> {
    const result = await this.conn.query<{ n: string }>(
      'SELECT COUNT(*) AS n FROM tool_invocations'
    )
    return Number(result.rows[0].n)
  }

  async queryToolInvocations(
    window: ToolInvocationWindow
  ): Promise<ToolInvocationAggregate[]> {
    const result = await this.conn.query<AggregateDbRow>(
      `SELECT
         tool_name AS tool,
         COUNT(*) AS calls,
         COUNT(*) FILTER (WHERE NOT ok) AS errors,
         AVG(duration_ms) AS avg_duration_ms,
         MAX(ts) AS last_used_at
       FROM tool_invocations
       WHERE ($1::text IS NULL OR ts >= $1)
         AND ($2::text IS NULL OR ts <= $2)
       GROUP BY tool_name`,
      [window.since, window.until]
    )
    return result.rows.map((r) => ({
      tool: r.tool,
      calls: Number(r.calls),
      errors: Number(r.errors),
      avgDurationMs: r.avg_duration_ms === null ? 0 : Number(r.avg_duration_ms),
      lastUsedAt: r.last_used_at
    }))
  }
}
